export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTO_EXITO = 'DESCARGA_PRODUCTO_EXITO'
export const DESCARGA_PRODUCTO_ERROR = 'DESCARGA_PRODUCTO_ERROR'

export const OBTENER_PRODUCTO_ELIMINAR ='OBTENER_PRODUCTO_ELIMINAR'
export const PRODUCTO_ELINIADO_EXITO ='PRODUCTO_ELINIADO_EXITO'
export const PRODUCTO_ELINIADO_ERROR ='PRODUCTO_ELINIADO_ERROR'